server:
  port: 9999
#
spring:
  application:
    name: bcp-bootcamp-gateway
  cloud:
    gateway:
      routes:
        - id: claims-eureka
          uri: lb://BOOTCAMP-HACKATON-CLAIMS
          predicates:
            - Path=/claims/**
#        - id: google-service
#          uri: https://www.google.com.pe
#          predicates:
#            - Path=/google/**
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
